#
# Jekyll configuration.
#
title:           Historical notes
description:     Historical notes.
url:             "http://desruisseaux.github.io"
baseurl:         ""
github_username: desruisseaux
email:           martin.desruisseaux@geomatys.com
theme:           minima
plugins:
  - jekyll-feed
